2023-05-01 14:23:17,087 - pymodbus.client.sync - ERROR - Connection to (169.254.0.35, 502) failed: timed out
2023-05-01 14:23:20,089 - pymodbus.client.sync - ERROR - Connection to (169.254.0.35, 502) failed: timed out
2023-05-01 14:23:23,093 - pymodbus.client.sync - ERROR - Connection to (169.254.0.35, 502) failed: timed out
2023-05-31 07:13:00,835 - pymodbus.client.sync - ERROR - Connection to (169.254.0.35, 502) failed: timed out
